datasources:
  default:
    url: jdbc:mariadb://${DB_HOST:db}/${DB_NAME:books}
    username: ${DB_USER:todo}
    password: ${DB_PASSWORD:todosecret}
jpa:
  default:
    properties:
      hibernate:
        show_sql: false
        format_sql: false

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9092`}