services:
  db:
    environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname books
  books:
    environment:
      DB_USER: *dbuser
      DB_PASSWORD: *dbpass
      DB_NAME: *dbname
      DB_HOST: db
